#!/bin/sh

# Create modem interface
uci set network.modem=interface
uci set network.modem.proto='modemmanager'
uci set network.modem.device='qcom-soc'
uci set network.modem.auth='none'
uci set network.modem.apn='internet'
uci set network.modem.allowedmode='4g|3g'
uci set network.modem.preferredmode='4g'
uci set network.modem.ifname='wwan0'
uci del_list firewall.@zone[1].network='modem'
uci add_list firewall.@zone[1].network='modem'

# We don't have eth0
uci -q del_list "network.@device[0].ports=eth0" 2>/dev/null || true
sed -i 's/"device": "eth0"/"device": "br-lan"/g' /etc/board.json

# Remove target-specific APK feed (msm89xx is not on downloads.openwrt.org)
sed -i '\|/targets/msm89xx/msm8916/packages|d' /etc/apk/repositories.d/distfeeds.list 2>/dev/null || true

# Add default modem configuration for luci-app-modemdata
uci add defmodems defmodems
uci set defmodems.@defmodems[-1].modem='qualcomm'
uci set defmodems.@defmodems[-1].modemdata='mm'
uci set defmodems.@defmodems[-1].comm_port='/org/freedesktop/ModemManager1/Modem/0'
uci set defmodems.@defmodems[-1].comm_mm='/org/freedesktop/ModemManager1/Modem/0'
uci set defmodems.@defmodems[-1].forced_plmn='0'
uci set defmodems.@defmodems[-1].forced_plmn_mm='0'
uci set defmodems.@defmodems[-1].network='modem'

uci commit
